networks:
  logstream:
    driver: bridge

services:
  # Fluentd service
  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: logstream-fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./simulator/logs:/var/log/simulator:ro
    networks:
      - logstream
    restart: unless-stopped
    environment:
      - FLUENTD_CONF=fluent.conf


  # Simulator for App 1
  simulator-app1:
    build:
      context: .
      dockerfile: ./simulator/Dockerfile
    container_name: logstream-simulator-app1
    environment:
      - APP_NAME=app1
    volumes:
      - ./simulator/logs:/usr/src/app/logs
    networks:
      - logstream
    restart: unless-stopped
    depends_on:
      - fluentd

  # Simulator for App 2  
  simulator-app2:
    build:
      context: .
      dockerfile: ./simulator/Dockerfile
    container_name: logstream-simulator-app2
    environment:
      - APP_NAME=app2
    volumes:
      - ./simulator/logs:/usr/src/app/logs
    networks:
      - logstream
    restart: unless-stopped
    depends_on:
      - fluentd

  # Simulator for App 3
  simulator-app3:
    build:
      context: .
      dockerfile: ./simulator/Dockerfile
    container_name: logstream-simulator-app3
    environment:
      - APP_NAME=app3
    volumes:
      - ./simulator/logs:/usr/src/app/logs
    networks:
      - logstream
    restart: unless-stopped
    depends_on:
      - fluentd
